# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# preparing selenium and chrome web driver manager
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

# importing os for running docker-compose up -d
import os


def test_login():
    driver = webdriver.Chrome(ChromeDriverManager().install())
    os.system('docker-compose up -d')

    driver.get("http://localhost:1667/#/")
    # driver.set_window_size(1050, 708)
    #driver.find_element(By.LINK_TEXT, "Sign in").click()
    driver.find_element_by_xpath('//a[@href="#/login"]').click()
    time.sleep(1)
    #driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    time.sleep(1)
    driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").send_keys("testuser1@example.com")
    time.sleep(1)
    driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys("Abcd123$")
    time.sleep(1)
    driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(2)
    #driver.quit()


test_login()
