# Generated by Selenium IDE
import pytest
import time
# preparing selenium and chrome web driver manager
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
# importing web driver waiting components
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# importing os for running docker-compose up -d
import os


@pytest.fixture(scope='session')
def browser():
    driver = webdriver.Chrome(ChromeDriverManager().install())
    os.system('docker-compose up -d')
    driver.get("http://localhost:1667/#/")
    return driver


# clicking on decline button and checking if it disappears
def test_decline_cookies(browser):
    time.sleep(1)
    decline_buttons = browser.find_elements_by_xpath('//div[@class="cookie__bar__buttons"]/button')
    assert (len(decline_buttons) > 0)
    decline_buttons[0].click()
    time.sleep(1)
    decline_buttons = browser.find_elements_by_xpath('//div[@class="cookie__bar__buttons"]/button')
    assert (len(decline_buttons) == 0)


# logging in and testing if the username appears correctly
def test_logging_in(browser):
    time.sleep(1)
    login = WebDriverWait(browser, 10).until(EC.visibility_of_element_located((By.XPATH, '//a[@href="#/login"]')))
    login.click()
    time.sleep(1)
    browser.find_element_by_xpath('//input[@type="text"]').send_keys("testuser1@example.com")
    time.sleep(1)
    browser.find_element_by_xpath('//input[@type="password"]').send_keys('Abcd123$')
    time.sleep(1)
    browser.find_element_by_xpath('//form/button').click()
    time.sleep(2)
    username = browser.find_element_by_xpath('//*[@id="app"]/nav/div/ul/li[4]/a').text
    assert (username == 'testuser1')
